### ISSUE TITLE
Leaves volume at zero

### ISSUE THREAD

**Issue by hampuseng** [vaddina/SpoMutify#1]
Great script! But sometimes it seems to overflow the volume when fading it up again so it leaves the music muted. I did an ugly fix just by adding "set sound volume to 100" after the repeat statement that fades the volume up. 

```
-- Increase Volume gracefully
repeat with i from currentVolume to (originalVolume+1) by 1
	set sound volume to i
	delay 0.02
end repeat
**set sound volume to 100**
```

**Comment by samsaara** [comment]
hey, thanks for pointing this out. I feel setting it to 100 might become unpleasant and can potentially harm you besides taking the user by sudden surprise. Can you submit a PR with resetting the volume to 70 or 75 or something if it overflows?
