### ISSUE TITLE
Posibility to run with launchctl

### ISSUE THREAD

**Issue by theodrim** [vaddina/SpoMutify#3]
Hello, and thanks for excellent script.
I have a quick question however - I've crafted following `plist` to start script in background on boot:
```
$ cat ~/Library/LaunchAgents/spotifymute.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.alex.spotmute</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/spomutify.sh</string>
    </array>
    <key>StartInterval</key>
    <integer>1800</integer>
</dict>
</plist>
$
```

But sadly it does nothing - I see process running, it just not doing the actual muting - do you know if `osascript` need some special permissions?
I do realize this might be out of scope of this project - so please feel free to close the issue.
Thank again!

**Comment by samsaara** [comment]
hey, thanks for your interest. Unfortunately I don't have any idea and I'm no longer working on this. So closing the issue. :slightly_smiling_face:
